export const ProjectData = {
    project1:{
        name:"project1",
        description:"",
        situation:"",
        task:"",
        action:"",
        result:"",
        image:""
    },
    project2:{
        name:"project2",
        description:"",
        situation:"",
        task:"",
        action:"",
        result:"",
        image:""
    },
    project3:{
        name:"project3",
        description:"",
        situation:"",
        task:"",
        action:"",
        result:"",
        image:""
    },
    project4:{
        name:"project4",
        description:"",
        situation:"",
        task:"",
        action:"",
        result:"",
        image:""
    }
}